### ISSUE TITLE
Editing new file crashes

### ISSUE THREAD

**Issue by edevil** [edubkendo/atom-elm#27]
If I try to edit a new file, before saving it, I get an error.

1. Edit new file (don't save it)
2. Type something.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [language-elm](https://github.com/edubkendo/atom-elm) package, v1.3.0

### Stack Trace

Uncaught Error: No elm-oracle suggestions

```
At /Users/andre/.atom/packages/language-elm/lib/provider.js:256

Error: No elm-oracle suggestions
    at noOutputFromOracleError (/Users/andre/.atom/packages/language-elm/lib/provider.js:227:10)
    at parseOutput (/Users/andre/.atom/packages/language-elm/lib/provider.js:256:11)
    at provideSuggestions (/Users/andre/.atom/packages/language-elm/lib/provider.js:59:15)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:467:12)
```

### Commands

```
     -0:48.3.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:47.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  4x -0:47.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:13.8.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "linter-xmllint"
    ]
  },
  "language-elm": {
    "elmOraclePath": "/Users/andre/.atom/packages/language-elm/node_modules/elm-oracle/bin/elm-oracle"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-elixir, v1.4.2
autocomplete-erlang, v1.1.1
autocomplete-python, v0.10.4
highlight-selected, v0.11.1
language-elixir, v0.5.2
language-elm, v1.3.0
language-erlang, v3.0.0
linter, v1.11.1
linter-clang, v3.3.0
linter-lua, v1.0.0
linter-pyflakes, v0.0.5
linter-pylint, v1.0.3
linter-python-pep8, v0.2.0
linter-shellcheck, v1.0.2
minimap, v4.16.0
python-isort, v0.0.7

# Dev
No dev packages
```

**Comment by brianegan** [comment]
Cool, thanks for the report! I'll take a look at it when I've got a bit of time on the weekend :)

**Comment by NicholasGW** [comment]
Does it work if you upgrade atom? I'm getting errors in the dev tools for this but no pop ups. Looks like it's related to trying to find the elm project path before the file is saved:  
  
          const elmProjectPath = findClosestElmProjectPath(filePath.split(pathSep).slice(0, -1));

Is throwing when trying to .split filePath
