### ISSUE TITLE
Support Elm 0.16

### ISSUE THREAD

**Issue by thSoft** [edubkendo/atom-elm#28]
Since I upgraded Elm Platform to 0.16, the following error is thrown when activating autocomplete:

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [language-elm](https://github.com/edubkendo/atom-elm) package, v1.3.0

### Stack Trace

Uncaught Error: No elm-oracle suggestions

```
At /Users/thsoft/.atom/packages/language-elm/lib/provider.js:256

Error: No elm-oracle suggestions
  at noOutputFromOracleError (/Users/thsoft/.atom/packages/language-elm/lib/provider.js:251:10)
  at parseOutput (/Users/thsoft/.atom/packages/language-elm/lib/provider.js:278:11)
  at provideSuggestions (/Users/thsoft/.atom/packages/language-elm/lib/provider.js:72:67)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```

### Commands

```
     -1:40.1.0 core:undo (atom-text-editor.editor.is-focused)
  2x -1:29.7.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -1:29.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:28.9.0 core:save (atom-text-editor.editor.is-focused)
  3x -1:27.2.0 core:close (atom-text-editor.editor.is-focused)
     -0:37.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:37.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:36.6.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -0:36.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:35.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:00.1.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "language-elm": {}
}
```

### Installed Packages

```coffee
# User
eclipse-keybindings, v0.8.0
language-elm, v1.3.0
linter, v1.10.0
linter-elm-make, v0.3.0
linter-jshint, v1.2.1
pigments, v0.18.1

# Dev
No dev packages
```

**Comment by NicholasGW** [comment]
Hey, just tried to reproduce on Windows and it seemed to work okay. Are you still having this issue? Only major difference is I'm running a newer version of Atom, 1.3.1.

**Comment by thSoft** [comment]
Okay, it is working with Atom 1.3.1!

**Comment by amitaibu** [comment]
I'm seeing the error as well when "Enable autocomplete" is enabled

<img width="661" alt="settings_-__library_webserver_documents_elm-learn_elm-hedley_-_atom" src="https://cloud.githubusercontent.com/assets/125707/11794545/3727d602-a2b2-11e5-896e-3bb10fc5b5f1.png">

**Comment by NicholasGW** [comment]
Hey amitaibu, are you using the latest version of atom as well? What's your setup like? Seems to be working for me so I'd like to try and reproduce.

**Comment by amitaibu** [comment]
>  are you using the latest version of atom as well?

I'll confirm on 1.3.2 (I think I have it on another computer, but I'll re-try)
