### ISSUE TITLE
Uncaught Error: No elm-oracle suggestions

### ISSUE THREAD

**Issue by liiklin** [edubkendo/atom-elm#47]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.5
**Thrown From**: [language-elm](https://github.com/edubkendo/atom-elm) package, v1.5.0
### Stack Trace

Uncaught Error: No elm-oracle suggestions

```
At /Users/linjun/.atom/packages/language-elm/lib/elmOracle.js:125

Error: No elm-oracle suggestions
    at parseOutput (/Users/linjun/.atom/packages/language-elm/lib/elmOracle.js:125:11)
    at provideSuggestions (/Users/linjun/.atom/packages/language-elm/lib/elmOracle.js:27:27)
    at triggerExitCallback (/Users/linjun/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at ChildProcess.<anonymous> (/Users/linjun/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```
### Commands

```
     -1:26.4.0 core:paste (atom-text-editor.editor.is-focused)
     -1:24.1.0 core:copy (atom-text-editor.editor.is-focused)
     -1:22.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:22.5.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -1:22 core:backspace (atom-text-editor.editor.is-focused)
     -1:21.7.0 core:paste (atom-text-editor.editor.is-focused)
     -1:21.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:20.3.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -1:19.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:18 blur (atom-text-editor.editor.is-focused)
  2x -1:13.1.0 core:save (atom-text-editor.editor.is-focused)
     -1:09.2.0 core:select-all (atom-text-editor.editor.is-focused)
  2x -1:08.4.0 core:save (atom-text-editor.editor.is-focused)
 13x -1:07.8.0 blur (atom-text-editor.editor.is-focused)
     -0:04.5.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -0:03.7.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "packagesWithKeymapsDisabled": []
  }
}
```
### Installed Packages

``` coffee
# User
api-workbench, v0.8.37 (active)
atom-beautify, v0.29.13 (active)
atom-mac-terminal, v1.0.4 (inactive)
autocomplete-python, v1.8.6 (active)
coffee-autocompile, v0.6.2 (active)
dash, v1.6.2 (inactive)
elm, v0.1.0 (active)
es6-javascript, v1.0.0 (inactive)
file-icons, v1.7.19 (active)
floobits, v0.32.4 (active)
hyperclick, v0.0.38 (active)
language-aspx, v0.5.0 (active)
language-docker, v1.1.7 (active)
language-elm, v1.5.0 (active)
language-nginx, v0.6.2 (active)
language-vue-component, v0.4.7 (active)
linter, v1.11.16 (active)
linter-elm-make, v0.17.7 (active)
pigments, v0.35.1 (active)
python-debugger, v0.1.0 (inactive)
python-nosetests, v0.2.0 (inactive)
thinkjs-snippets, v0.1.0 (active)
tree-view-git-status, v1.1.0 (active)
vue-format, v0.4.0 (inactive)
vue-snippets, v0.6.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by mm-tfx** [comment]
I think I have the same problem but when running this on Windows.
I have tried several different paths to point elm-oracle but neither works.

**Comment by lurodrigo** [comment]
same problem on windows

**Comment by mm-tfx** [comment]
I finally made it to work on Windows 10. I have installed elm-oracle an it has been added to PATH. Then I just add 'elm-oracle' in the setting field and it works now.

**Comment by jwogrady** [comment]
Still seems to be an issue on OSX using atom.  Here is my stacktrace.

```
Error: No elm-oracle suggestions
    at parseOutput ({/Users/{myusername}}atom/packages/language-elm/lib/elmOracle.js:125:11)
    at provideSuggestions ({/Users/{myusername}}atom/packages/language-elm/lib/elmOracle.js:27:27)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:222:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

```
My /user/local/bin already added to path, so not sure the Window's fix is a solution for me.

**Comment by LA1CH3** [comment]
In case anyone missed this from the package readme:

> Open up a terminal
> npm install -g elm-oracle
> which elm-oracle on Unix/Linux or where.exe elm-oracle on Windows
> Copy the path to elm-oracle
> Open up the language-elm settings in Atom
> Open up the Atom Settings / Preferences tab
> Click on "Packages"
> Find the "language-elm" package in the list
> Click "Settings"
> Paste the path into "The elm-oracle executable path" setting

**Comment by kjda** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [language-elm](https://github.com/edubkendo/atom-elm) package 1.5.0


### Stack Trace

Uncaught Error: No elm-oracle suggestions

```
At /Users/{u}/.atom/packages/language-elm/lib/elmOracle.js:125

Error: No elm-oracle suggestions
    at parseOutput (/packages/language-elm/lib/elmOracle.js:125:11)
    at provideSuggestions (/packages/language-elm/lib/elmOracle.js:27:27)
    at triggerExitCallback (/app.asar/src/buffered-process.js:303:11)
    at /app.asar/src/buffered-process.js:316:11
    at /app.asar/src/buffered-process.js:185:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -5:12.7.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -5:12.3.0 core:backspace (input.hidden-input)
  2x -5:12.1.0 core:save (input.hidden-input)
     -4:21.9.0 core:move-right (input.hidden-input)
  3x -4:19.5.0 core:save (input.hidden-input)
     -3:32.5.0 core:move-right (input.hidden-input)
     -3:32.2.0 core:backspace (input.hidden-input)
     -3:31.7.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -3:31.5.0 core:move-left (input.hidden-input)
  3x -3:27 core:save (input.hidden-input)
  3x -1:58.6.0 core:backspace (input.hidden-input)
  2x -0:18.4.0 editor:newline (input.hidden-input)
     -0:10.2.0 core:move-up (input.hidden-input)
  2x -0:09.7.0 core:move-right (input.hidden-input)
     -0:06.3.0 core:backspace (input.hidden-input)
     -0:05.8.0 core:move-right (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-modules 1.6.7 
editorconfig 2.2.1 
elm 0.1.0 
elm-format 2.1.0 
elmjutsu 4.0.0 
go-debug 1.0.4 
go-imports 0.1.1 
go-outline 0.6.6 
go-plus 5.1.1 
go-signature-statusbar 1.2.0 
go-tip 2.4.0 
gpp-compiler 3.0.7 
hyperclick 0.0.40 
language-babel 2.54.1 
language-elm 1.5.0 
linter 1.11.23 
linter-elm-make 0.22.2 
linter-eslint 8.1.2 
linter-gcc 0.7.1 
linter-golint 0.3.0 
linter-golinter 1.2.1 
linter-js-standard 3.8.1 
linter-js-standard-jsx 4.1.2 
open-path 0.3.6 
platformio-ide-terminal 2.2.3 
```
