### ISSUE TITLE
Uncaught Error: No elm-oracle suggestions

### ISSUE THREAD

**Issue by mauradelrosario** [edubkendo/atom-elm#52]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [language-elm](https://github.com/edubkendo/atom-elm) package 1.5.0

### Stack Trace

Uncaught Error: No elm-oracle suggestions

```
At /Users/maurarodriguez/.atom/packages/language-elm/lib/elmOracle.js:125

Error: No elm-oracle suggestions
    at parseOutput (/packages/language-elm/lib/elmOracle.js:125:11)
    at provideSuggestions (/packages/language-elm/lib/elmOracle.js:27:27)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:335:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -0:54.9.0 core:select-all (input.hidden-input)
     -0:53.8.0 core:paste (input.hidden-input)
     -0:52 core:undo (input.hidden-input)
  4x -0:28.9.0 core:backspace (input.hidden-input)
     -0:03.0 core:select-up (input.hidden-input)
     -0:02.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.3.0 
elm-format 2.1.0 
intentions 1.1.2 
language-elm 1.5.0 
linter 2.1.0 
linter-elm-make 0.23.2 
linter-ui-default 1.1.0 
react 0.16.2 
```

**Comment by patrickdet** [comment]
same here

**Comment by duncanmalashock** [comment]
I'm getting this too

**Comment by angierovatti** [comment]
same here :(

**Comment by cgarciae** [comment]
+1

**Comment by groundedsage** [comment]
+1

**Comment by jigargosar** [comment]
+1

**Comment by gurujimani** [comment]
+1

**Comment by knutanderss** [comment]
+1

**Comment by suside** [comment]
In my case it was just:
```
elm-make: elm-stuff/build-artifacts/0.18.0/user/project/1.0.0/Modules-Announcements-ItemView.elmi: openBinaryFile: permission denied (Permission denied)
elm-make: thread blocked indefinitely in an MVar operation
```
after fixing permissions everything works as expected.

**Comment by Tmarty** [comment]
In my case I was missing the elm-oracle package and needed to install and configure the plugin with it's path.

**Comment by slaaxy** [comment]
This just randomly started happening, 30 minutes ago it worked just fine then I restarted atom and suddenly it wont work. I double checked so that the path to elm-oracle is correct, also verified that it works outside of atom, providing it with a file/query works as expected. 

`.atom/packages/language-elm/lib/elmOracle.js:125
Hide Stack Trace
Error: No elm-oracle suggestions
    at parseOutput (/home/jerry/.atom/packages/language-elm/lib/elmOracle.js:125:11)
    at provideSuggestions (/home/jerry/.atom/packages/language-elm/lib/elmOracle.js:27:27)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:338:17)
    at /usr/share/atom/resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)`

**Comment by bmordan** [comment]
+1

**Comment by nlko** [comment]
In my case I was missing elm-oracle package.

Using node v7.9.0 (`nvm use v7.9.0`), i did `npm -g install elm-oracle`

**Comment by xpe** [comment]
As of March 2016 (over two years ago), Github added a feature called reactions (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) so that people don't need to respond "same here" and "+1".

**Comment by alexpreiss** [comment]
> In my case it was just:
> 
> ```
> elm-make: elm-stuff/build-artifacts/0.18.0/user/project/1.0.0/Modules-Announcements-ItemView.elmi: openBinaryFile: permission denied (Permission denied)
> elm-make: thread blocked indefinitely in an MVar operation
> ```
> after fixing permissions everything works as expected.

How did you fix the permissions?
I have the same exact error
